### ISSUE TITLE
model's inference

### ISSUE THREAD

**Issue by gmk11** [labITS-stt-eesc/Axle_Detection#1]
Hi, i found your work and it's very interesting , could you please explain how to do inference on a image/video with your models ? I tried by executing test.py (for YOLOV3 ) but it didn't worked for me

**Comment by leandromarcomini** [comment]
Hello!

Due to file size limitations on github, i cannot upload a trained network file. It should be located in the "Model_Weights" folder, and the file name should be changed accordingly. You can change it in [line 77, in the test.py file](https://github.com/labITS-stt-eesc/Axle_Detection/blob/948b707d15c68a40f0540bd2c7ced3827c2ac2d1/YOLOV3/test.py#LL77C110-L77C110). You need to first train your network, so then you can use it for inference later.

**Comment by gmk11** [comment]
Hello! 
@leandromarcomini I thought you had a model zoo or a google link where the weights model's were stored. it could be a good idea.  
Thank you for your response .

**Comment by leandromarcomini** [comment]
It is something we will consider in the future, since we already share our [image database on Zenodo](https://zenodo.org/record/7695824). You basically "just" need to train the network, using one the the base weight files available for YOLOv3.
